server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: java-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: my-app
          __path__: /var/log/app/*.log
